version: '3.8'

services:
    db:
        image: postgres:16
        container_name: ibuy-postgres-db
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: myapp
        ports:
            - '5432:5432'
        volumes:
            - ibuy_data:/var/lib/postgresql/data
            - ./db/tables.sql:/docker-entrypoint-initdb.d/tables.sql:ro
        networks:
            - app-network
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U user -d myapp']
            interval: 30s
            timeout: 10s
            retries: 3

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: ibuy-server
        ports:
            - '8080:8080'
        env_file:
            - ./server/.env
        environment:
            - DATABASE_URL=postgres://user:password@db:5432/myapp?sslmode=disable
            - DB_USER=user
            - DB_PASSWORD=password
            - DB_NAME=myapp
            - DB_HOST=db
            - DB_PORT=5432
            - SERVER_PORT=8080
        volumes:
            - ./uploads:/app/uploads
        depends_on:
            db:
                condition: service_healthy
        networks:
            - app-network
        restart: unless-stopped

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: ibuy-client
        ports:
            - '3000:80'
        env_file:
            - ./client/.env
        environment:
            - VITE_SERVER_API=http://localhost:8080/
        volumes:
            - ./uploads:/app/uploads:ro
        depends_on:
            - server
        networks:
            - app-network
        restart: unless-stopped

networks:
    app-network:
        driver: bridge

volumes:
    ibuy_data:
